### ISSUE TITLE
cmd/unity: project mode bug when a cue.mod vendored dependency is a module

### ISSUE THREAD

**Issue by myitcv** [cue-sh/unity#59]
Reported by @eonpatapon 

This is likely a simple bug in the directory walking logic: it should not walk within `cue.mod`.

**Comment by verdverm** [comment]
Is this when my test has a CUE module that it imports, which is stored in git in the `cue.mod/pkg/domain.com/myorg/mymod`?

I think this is the setup I need and this issue is relevant(?).

My tests would rely on CUE modules stored in other git repos which I place into the `cue.mod/pkg/...` directory. I don't vendor them at present, but given #60 (where I wanted to use git to fetch them), this was my next option (?)
